# Generated by Django 2.2 on 2020-02-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20191025_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='lister',
            field=models.ForeignKey(on_delete=False, related_name='dates', to='app1.Lister'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='dates', to='app1.User'),
        ),
    ]
